site:
  name: sample
  hosted_zone: sample.com
  certificate_arn: arn:aws:acm:us-west-2:123:certificate/asdf
  s3_website: s3_website_us_west_2.amazonaws.com
  s3_hosted_zone: Z3BJ6K6RIION7M
  file_path: example-site/
